name: CDK Deploy
on:
 push:

jobs:
 cdk-diff:
  runs-on: ubuntu-latest
  env:
   AWS_REGION: us-east-2
  permissions:
   id-token: write
   contents: read
  steps:
   - name: Wait
     run: sleep 5 # give the runtime 5 seconds to initialize

  #  - name: Checkout
  #    uses: actions/checkout@v2

   - name: Configure AWS Variables
     shell: bash
     env:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
      AWS_DEFAULT_REGION: us-east-2
     run: |
      echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
      echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
      echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV
      curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
      cat /tmp/awscreds
   - run: aws sts get-caller-identity
